title: My Website
description: A simple static website hosted on GitHub Pages
baseurl: ""  # Keep this empty if deploying at root (e.g., username.github.io/repo)
url: "https://hashdevbytes.github.io/bethere"

# Disable Jekyll SCSS processing


# Exclude unnecessary files from Jekyll processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .nojekyll
  - node_modules/
  - vendor/
